"""Add guardian_name to student

Revision ID: e7fb49b82135
Revises: b9c7af7f5cd1
Create Date: 2026-08-06 17:17:55.371966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7fb49b82135'
down_revision: Union[str, Sequence[str], None] = 'b9c7af7f5cd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('guardian_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'guardian_name')
    # ### end Alembic commands ###
